# Generated by Django 4.2.22 on 2025-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
