# Generated by Django 4.2.22 on 2025-07-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_internshipapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
