# Generated by Django 4.2.22 on 2025-07-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recruiterverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterverification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='recruiterverification',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterverification',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiterverification',
            name='id_proof',
            field=models.FileField(upload_to='recruiter_proofs/'),
        ),
        migrations.AlterField(
            model_name='recruiterverification',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
